version: '3.8'

services:
  cattus-app:
    build: .
    container_name: cattus-activities-identifier
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always